# Site settings
title: DaunStore
subtitle: by <strong>DaunScape</strong> 🍀
email: store@daunscape.tech
description: >- # this means to ignore newlines until "baseurl:"
  DaunStore is your trusted digital store, created by DaunScape
  to deliver managed digital services tailored to your needs.
  We offer a wide range of solutions to help you achieve your digital goals,
  combining affordability with top-notch quality and dedicated support.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed
# plugins:
#   - jekyll-feed
